### ISSUE TITLE
Ideas for going forward

### ISSUE THREAD

**Issue by zoni** [gbin/err#125]
(Ab)using this issue as a place to brainstorm about future ideas and what to focus on first.

I have a couple of items on my "Err to-do" list, and could use some feedback from the community on what they'd like to see prioritized/added. Any and all fresh ideas are welcome. Give me something good and I'll add it to the list! :) (but I'm not promising I'll work on it though ;) )

- [ ] *Website*: I think Err is one of the most feature-complete bots out there and I see potential for even more growth in the future. The site could use a bit of love to showcase Err and highlight it's core features, perhaps include some documentation directly on the website as well on how to write plugins, emphasizing how easy it to write your own plugins. ~~Also, the webchat is 404'ing right now, and webchat on master is totally broken.~~
- [ ] *Documentation*: There definitely needs to be some documentation love. I could use some help narrowing down what needs the most attention, though. 
  -  The page on [plugin dev](https://github.com/gbin/err/wiki/plugin-dev) is a bit of a scattering of random bits of information you can puzzle together to make a working plugin. Some more buildup here and a good reference might be helpful?
  -  Installing Err.. Is there clear enough info on this?
  - I think we should document info on how to access the bot's buddy list and dealing with sending/receiving buddy list invitations and such.. I could see plugins being made that hook into this.
- [ ] *Plugins*: I have this idea to remove repos.py and make it get loaded dynamically from a url in YAML or JSON format. This way your config could contain a list of URL's where it can get a list of available plugins (kind of like repositories for Linux distributions). Then we can have stuff like a list of official plugins, a separate list of experimental plugins and, for companies, you could have an in-house list that isn't accessible to the outside world for example.
- [ ] *buddylist access*: It would be nice for plugins to be able to easily access and manipulate the bot's buddylist.
- [x] *Presence state access/callbacks*: It would be nice if plugins received and could act on XMPP presence stanza's.

**Comment by gbin** [comment]
most of those are done, maybe we could restart a new brainstorm?
