### ISSUE TITLE
Add the possibility to make txt templates for responses instead of letting err strip the xhtml content

### ISSUE THREAD

**Issue by gbin** [gbin/err#166]
What could be nice to implement, as in the api the user doesn't have to specify an extension is to take the "template_name.html" as the html template and "templane_name.txt" as the text one.

It would need some refactoring in the backends as they are dealing with this conversion now (and they should be spared and given the already baked xhtml AND txt version instead of calling build_text_html_message_pair themselves)

**Comment by brycied00d** [comment]
For what it's worth, I did find a hacky way to accomplish a subset of this, including a plaintext url for text clients that doesn't get rendered in XHTML. The URL is "commented out" (with a funky-looking closing tag) so XHTML strips out the comment. When the plaintext version is derived, the tags are simply stripped away and the text between them remains.

```
{%- extends "base.html" %}
{%- block body %}
{%- if error %}<span style='font-weight:bold; color:red'>Error!</span> {{ issue|trim|e }}
{%- else %}{% if json['user']['avatar_url'] %}<img src="{{ json['user']['avatar_url']|e }}">{% endif %}{{ json['user']['name']|e }} has just {{ json['object_attributes']['action']|e }}ed issue <a href="{{ json['object_attributes']['url']|e }}">#{{ json['object_attributes']['iid']|e }}</a>, "<a href="{{ json['object_attributes']['url']|e }}">{{ json['object_attributes']['title']|e }}</a>" {{ json['object_attributes']['url']|e }}
{#- The next line shows the URL to textual clients, but it gets hidden/stripped-out by the html "tags" when rendered #}
{%- if True %}{{ ' <!--'|safe }} <a>{{ json['object_attributes']['url']|e }}</a> {{ '<-->'|safe }}{% endif %}
{%- endif %}
{%- endblock %}
```

**Comment by gbin** [comment]
let's continue this one on #395
