### ISSUE TITLE
Unable to get 2.0 Beta Working Under Windows.

### ISSUE THREAD

**Issue by linuxtechie** [gbin/err#167]
Guys,

I can get 1.71. working under windows by removing python-daemon. I have been using ActivePython 2.7 for about some 4 months in our R&D. It's being used along with selenium and other in-house tools as a crude plug n play non centralized distributed RPC kinda things.

Now back to 2.0, I know its beta, but its not working :(

**Comment by gbin** [comment]
I would like to start a new issue about detecting if the user is doing that : starting the py2 version under py3 or py3 version under py2
