### ISSUE TITLE
Flowdock integration

### ISSUE THREAD

**Issue by AdeTheux** [gbin/err#169]
**Not really an issue...**

If anyone is interested I'm trying to create a backend for Flowdock. Or use this: https://github.com/Aeron/PyFlowdock

But I'm a big noob so it will probably take ages :)

I began by modifying the config.py to duplicate the HipChat connection to create if for Flowdock.
Then I found the library above which seems easier to use. But I'm still figurging out how to use it.

**Comment by gbin** [comment]
@aadis can you PR a fix for this ?

**Comment by aadis** [comment]
I hacked it in, but let me see if I find the time to do a PR.

[our copy of err is also hacked to force unicode in bunch of places, and do deal with how flowdock does context chat]

**Comment by gbin** [comment]
Now that backends are plugins, if anybody is courageous enough to make a flowdock backend, feel free to do it and head to the gitter chatroom if you encounter problems implementing it.
