### ISSUE TITLE
which('git') doesn't seem to work on windows

### ISSUE THREAD

**Issue by matthebs** [gbin/err#186]
Returns nothing. I have git installed and it doesn't work, how can i install plugins manually?

**Comment by dmsimard** [comment]
The master branch doesn't seem to work right now for which.

    >>> !repos update all
    15:38:31 INFO     errbot.errBot             Processing command 'repos_update' with parameters 'all' from d
    15:38:31 ERROR    errbot.errBot             An error happened while processing a message ("!repos update all"): Traceback (most recent call last):
     File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 363, in _execute_and_send
       reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
     File "/usr/local/lib/python2.7/dist-packages/errbot/core_plugins/plugins.py", line 89, in repos_update
       git_path = which(u'git')
    NameError: global name 'which' is not defined
    "
    Traceback (most recent call last):
     File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 363, in _execute_and_send
       reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
     File "/usr/local/lib/python2.7/dist-packages/errbot/core_plugins/plugins.py", line 89, in repos_update
       git_path = which(u'git')
    NameError: global name 'which' is not defined

    ââ[MD  ]ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
    Computer says nooo. See logs for details.:
    global name 'which' is not defined


    ââ[HTML]ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
    <p>Computer says nooo. See logs for details.:
    global name 'which' is not defined</p>


    ââ[TEXT]ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
    Computer says nooo. See logs for details.:
    global name 'which' is not defined

    ââ[ANSI]ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
    Computer says nooo. See logs for details.:
    global name 'which' is not defined

**Comment by gbin** [comment]
@dmsimard thx for spotting this ! 45fd23b962c801d3dabd3dbfb75c1a9a8e8a78c5 should fix it.

**Comment by gbin** [comment]
while I am at it I have pushed a fix for the original problem, please reopen it if it doesn't work.
6723d340780b492f6ffb728b0407c06c1f4e3703
