### ISSUE TITLE
ErrBot hanging after some time

### ISSUE THREAD

**Issue by aadis** [gbin/err#190]
Here are the logs:

<pre>
DEBUG:root:Wait 0.049997 due to rate limiting...
DEBUG:irc.client:TO SERVER: PRIVMSG #idvc/hangout :Advani to skip Modi's Oct 27 Patna rally - Business Standard
DEBUG:root:All plugins: [<yapsy.PluginInfo.PluginInfo object at 0x1476e90>, <yapsy.PluginInfo.PluginInfo object at 0x28f0a90>, <yapsy.PluginInfo.PluginInfo object at 0x1480090>, <yapsy.PluginInfo.PluginInfo object at 0x14130d0>, <yapsy.PluginInfo.PluginInfo object at 0x140be10>]
DEBUG:root:All plugins: [<yapsy.PluginInfo.PluginInfo object at 0x1476e90>, <yapsy.PluginInfo.PluginInfo object at 0x28f0a90>, <yapsy.PluginInfo.PluginInfo object at 0x1480090>, <yapsy.PluginInfo.PluginInfo object at 0x14130d0>, <yapsy.PluginInfo.PluginInfo object at 0x140be10>]
DEBUG:root:Callback <yapsy_loaded_plugin_ChatRoom_0.ChatRoom object at 0x18b0310>
DEBUG:root:Callback <yapsy_loaded_plugin_DevOpsBorat_0.DevOpsBorat object at 0x2cb1d50>
DEBUG:root:Callback <yapsy_loaded_plugin_idbot_0.idbot object at 0x212da10>
DEBUG:root:IDBOT: from: #idvc/hangout target:#idvc/hangout body:.news type:groupchat
DEBUG:root:Callback <yapsy_loaded_plugin_Webserver_0.Webserver object at 0x1bc8350>
DEBUG:root:Callback <yapsy_loaded_plugin_VersionChecker_0.VersionChecker object at 0x18b0490>
</pre>

If I run a strace I see this never ending stream:

<pre>
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
select(5, [4], [], [], {0, 200000})     = 0 (Timeout)
</pre>

And today I see this:

<pre>
IRCBackend.about clashes with IRCBackend.about so it has been renamed ircbackend-about
IRCBackend.apropos clashes with IRCBackend.apropos so it has been renamed ircbackend-apropos
IRCBackend.config clashes with IRCBackend.config so it has been renamed ircbackend-config
IRCBackend.echo clashes with IRCBackend.echo so it has been renamed ircbackend-echo
IRCBackend.export_configs clashes with IRCBackend.export_configs so it has been renamed ircbackend-export_configs
IRCBackend.history clashes with IRCBackend.history so it has been renamed ircbackend-history
IRCBackend.help clashes with IRCBackend.help so it has been renamed ircbackend-help
IRCBackend.import_configs clashes with IRCBackend.import_configs so it has been renamed ircbackend-import_configs
IRCBackend.load clashes with IRCBackend.load so it has been renamed ircbackend-load
IRCBackend.log_tail clashes with IRCBackend.log_tail so it has been renamed ircbackend-log_tail
IRCBackend.reload clashes with IRCBackend.reload so it has been renamed ircbackend-reload
IRCBackend.repos clashes with IRCBackend.repos so it has been renamed ircbackend-repos
IRCBackend.repos_export clashes with IRCBackend.repos_export so it has been renamed ircbackend-repos_export
IRCBackend.repos_install clashes with IRCBackend.repos_install so it has been renamed ircbackend-repos_install
IRCBackend.repos_uninstall clashes with IRCBackend.repos_uninstall so it has been renamed ircbackend-repos_uninstall
IRCBackend.repos_update clashes with IRCBackend.repos_update so it has been renamed ircbackend-repos_update
IRCBackend.restart clashes with IRCBackend.restart so it has been renamed ircbackend-restart
IRCBackend.status clashes with IRCBackend.status so it has been renamed ircbackend-status
IRCBackend.unload clashes with IRCBackend.unload so it has been renamed ircbackend-unload
IRCBackend.uptime clashes with IRCBackend.uptime so it has been renamed ircbackend-uptime
1:40
IRCBackend.zap_configs clashes with IRCBackend.zap_configs so it has been renamed ircbackend-zap_configs
</pre>

**Comment by gbin** [comment]
I had the same issue *once* with err on the IRC bridge to gitter but it took days of uptime to occur.

**Comment by aadis** [comment]
This could be the flowdock irc server gateway, but the cron hack works for me...

**Comment by gbin** [comment]
I have added the disconnect event handling, it should be fixed now on head, please reopen if you see that again. Thx for your patience on this one !
