### ISSUE TITLE
Plugin python requirements / supported version flags

### ISSUE THREAD

**Issue by apophys** [gbin/err#240]
A lot of plugins that are included in the distribution (as links to repos) doesn't have a version of python specified and Err assumes they support python 2 only.

The only plugins with version specified are these:
err-dnsnative/dnsnative.plug:Version = 3
err-dnsutils/dnsutils.plug:Version=2+
err-faustbot/faust.plug:Version=2+
err-markovbot/markov.plug:Version=2+

The rest of them is currently unusable on python 3 deployments. At least without some effort spent to edit the plugin file and test the code. Not much user friendly.

[This issue could be related](https://plus.google.com/103419671297484826120/posts/FwkvinCcpi4). I don't know what would be the right thing to do here, but there are some options. Ranging from porting the plugins to dropping python 2 support. :)

**Comment by gbin** [comment]
I think this can be closed: the situation improved a lot since last year, most of the plugins have been ported to python3, I pinged the authors with issues or PR'd their plugin for the few remaining.
