### ISSUE TITLE
deprecation warning: sleekxmpp.xmlstream.xmlstream:Use of send mask waiters is deprecated.

### ISSUE THREAD

**Issue by daenney** [gbin/err#291]

**Comment by gbin** [comment]
Looked into it, so basically sleekxmpp exposes a wait=True feature when you join a MUC with xep0045, this in turn joins a MUC then wait in the stream with a kind of "expect" your own presence, this guaranties that when the call returns, you are actually in the room.

The thing is they deprecated internally this "expect" feature, with no replacement. This is a weird situation as wait doesn't seem to be deprecated itself. It is totally an internal problem of sleekxmpp.

I close this one as won't fix.
