### ISSUE TITLE
Keepalives no longer being sent

### ISSUE THREAD

**Issue by zoni** [gbin/err#319]
Whitespace keep-alive events are no longer being sent by SleekXMPP, resulting in time-outs on HipChat. This is most likely a regression due to #314 but I haven't looked into it yet.

**Comment by reiven** [comment]
Yes, i'm having this issue too.
There is any workaround for it?

**Comment by BobbyD-FL** [comment]
try decreasing the keepalive.

XMPP_KEEPALIVE_INTERVAL = 60

**Comment by reiven** [comment]
That worked for me. Thanks @BobbyD-FL
