### ISSUE TITLE
Unable to send private response to MUC commands

### ISSUE THREAD

**Issue by ghost** [gbin/err#321]
I recently started poking about with Err for work, and one thing I'd like to be able to do is have a user throw out a command in a MUC and have Err respond via PM. I've thumbed through some older issues that show that you cannot get to normal JID from commands in a MUC, but several posts seem to show that you can respond to the MUC-specific JID. So far, I can't seem to get that to work.

Note: This is using HipChat.

Whenever I send a command, I've tried doing a self.send() to msg.getFrom() and manually putting it in there (12345_1234567@chat.hipchat.com/Nick Name) and both return the same response:

```
DEBUG:root:Determined that [Test Message] is not XHTML-IM (syntax error: line 1, column 0)
DEBUG:root:All plugins: VersionChecker, ChatRoom, Escalations, Webserver
DEBUG:sleekxmpp.xmlstream.xmlstream:SEND: <message to="12345_roomname@conf.hipchat.com/Nick Name" type="chat" xml:lang="en"><body>Test Message</body></message>
DEBUG:sleekxmpp.xmlstream.xmlstream:RECV: <message type="error" from="12345_roomname@conf.hipchat.com/Nick Name" to="12345_1234567@chat.hipchat.com/none||proxy|pubproxy-c20.hipchat.com|5232"><body>Test Message</body><error code="400" type="modify"><jid-malformed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></message>
DEBUG:sleekxmpp.xmlstream.xmlstream:Event triggered: message
DEBUG:sleekxmpp.xmlstream.xmlstream:Event triggered: groupchat_message_error
DEBUG:sleekxmpp.xmlstream.xmlstream:Event triggered: muc::12345_roomname@conf.hipchat.com::message_error
DEBUG:root:unhandled message type Test Message
```

From what I've seen looking through older issues, similar issues have come up and are either super out-of-date (mid-2012ish) or were closed and I'm unable to see what was changed.

Is there a way to respond to a command issues in a MUC via PM, under HipChat? Seems like this is more a limitation of HipChat, rather than Err, which makes me hesitant to try another bot... but unfortunately, what I'm trying to do is pretty reliant on this functionality.

EDIT: ~~Apologies for a second comment, not sure what protocol is. I'm starting to think maybe the issue is the janky resource set for the bot (none||proxy|pubproxy-c20.hipchat.com|5232)? It's running locally on my Mac for now, but I wonder if there's a way to set that resource myself to something simpler?~~ Just kidding. I can see that the command sent uses the same resource names, so that can't be it. :|

**Comment by zoni** [comment]
It appears something has broken with some recent changes, as `DIVERT_TO_PRIVATE` doesn't work on HipChat either at the moment. I'll try to look into that, though I'm a little busy at the moment so I can't tell exactly when that will be.

**Comment by gbin** [comment]
I tried to fix it by using their v2 API directly but it doesn't work because bots cannot send direct messages. (the API returns a 204 but happily ignores the message <- this is the smell of a crappy API)

**Comment by gbin** [comment]
won't fix as it is an unsolvable hipchat problem.
