### ISSUE TITLE
requirements.txt out of date?

### ISSUE THREAD

**Issue by matthijskooijman** [gbin/err#325]
I just tried installing dependencies from requirements.txt, which inludes "[config](https://pypi.python.org/pypi/config)". However, installing if fails, that module seems to be python2-only. I see that setup.py also lists dependencies - is requirements.txt not used anymore? If so, shouldn't it be removed?

**Comment by gbin** [comment]
I just installed it on a clean virtual env under python 3 with pip -r requirements.txt and it looks like it is there:
(err)minisal ➜  err (master) pip show config  
---
Name: config
Version: 0.3.9
Location: /home/gbin/.virtualenvs/err/lib/python3.4/site-packages
Requires: 

Which is weird because it is clearly tagged as a py2 package indeed.

**Comment by gbin** [comment]
Maybe we need to adopt this kind of tricks because our requirements are too dynamic ? https://gist.github.com/pombredanne/72130ee6f202e89c13bb

**Comment by amorphic** [comment]
Just my $0.02:

You should probably only be using `install_requires` in `setup.py` to define the package dependencies. The `requirements.txt` file is better used by build processes and the like to create a "known good" environment for deployment.

These articles explain the reasoning better than I could but to summarize: _"`setup.py` is designed for redistributable things and `requirements.txt` is designed for non-redistributable things."_

https://caremad.io/2013/07/setup-vs-requirement/
http://cramer.io/2012/04/24/sticking-with-standards/

**Comment by gbin** [comment]
The trick from the first link is interesting :

    --index-url https://pypi.python.org/simple/
    -e .

**Comment by gbin** [comment]
done it here https://github.com/gbin/err/pull/359
