### ISSUE TITLE
Plugin skeleton .plug file is missing Python section

### ISSUE THREAD

**Issue by matthijskooijman** [gbin/err#326]
Reporting here, since https://github.com/gbin/err-skeleton doesn't have issues. As per subject - using the skeleting .plug file gives me:

```
21:54:00 WARNING  root                      Plugin Factoid has no section [Python]. Assuming this plugin is runnning only under python 2.
21:54:00 ERROR    root                      
Plugin Factoid is made for python 2 only and you are running err under python 3.

If the plugin can be run on python 2 and 3 please add this section to its .plug descriptor :
[Python]
Version=2+

Or if the plugin is Python 3 only:
[Python]
Version=3
```

**Comment by gbin** [comment]
Thx for reporting that, can you open a pull request directly ? 
Thx !

**Comment by matthijskooijman** [comment]
No time for that, sorry.

**Comment by zoni** [comment]
Fixed in https://github.com/zoni/err-skeleton/commit/ebb28999da95b2d52c59ba63fa2ff52d9ea032d4. @gbin will have to merge this in his fork because I don't have collaborator status for that repo.

**Comment by gbin** [comment]
Done thx.
