### ISSUE TITLE
Reference other plugins

### ISSUE THREAD

**Issue by sijis** [gbin/err#330]
Is there a way to reference other plugins from another plugin?

This is the rough idea:
I have a plugin that needs to do a dns lookups and do an action based on what IP (or other data) is returned. Instead of writing my own method or re-implementing a similar one, I would leverage an existing plugin's functionality (let's say the err-dnsutils module). In my plugin I would be able to call the dns plugin, get the output I requested and let my plugin continue with its functionality.

The inspiration is based on some functionality on the salt project module system.
https://salt.readthedocs.org/en/latest/ref/modules/index.html#cross-calling-modules

**Comment by gbin** [comment]
Hi,

I think it is a good idea but at the wrong abstraction level: 
- a library is designed to talk to code
- a plugin is designed to talk to humans

Here having a common python package as a dependency for both plugins would be better.

Having said that, we might have to look on how we can manage library dependencies better from the plugins installations, the user experience is a little rough as it is implemented. I would wish for a more automated way of importing stuff from plugins and more isolation, maybe making a small virtualenv where they can install stuff for themselves.
