### ISSUE TITLE
Change bot data directory

### ISSUE THREAD

**Issue by AquilaSagitta** [gbin/err#332]
<code>$ err.py -d</code>
    INFO:root:Config check passed...
    INFO:root:Checking for '/var/lib/err'...
    Traceback (most recent call last):
      File "/home/aquila/botenv/bin/err.py", line 171, in <module>
        raise Exception(u"The data directory '%s' for the bot does not exist" % BOT_DATA_DIR)
    Exception: The data directory '/var/lib/err' for the bot does not exist

I don't have access to create that directory. Is it possible to change it to somewhere I have access without editing source code?

**Comment by gbin** [comment]
You need a config.py from where you start the bot like this file : https://github.com/gbin/err/blob/master/errbot/config-template.py

Here you can tell where the not should store its data.

**Comment by AquilaSagitta** [comment]
I changed data and log files location and now I'm getting this error. I don't see anything in config that corresponds to this.

<code>$ err.py</code>
INFO:root:init plugin manager
INFO:root:Config check passed...
INFO:root:Checking for '/home/aquila/bluefireBOT'...
Traceback (most recent call last):
  File "/home/aquila/botenv/bin/err.py", line 202, in <module>
    main(bot_class, logger)
  File "/home/aquila/botenv/local/lib/python2.7/site-packages/errbot/main.py", line 14, in main
    hdlr = logging.FileHandler(BOT_LOG_FILE)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/var/log/err/err.log'

**Comment by gbin** [comment]
Do you have a config.py in the directory from where you start the bot ?
Try "cat config.py" from where you execute err.py it should show the customized config you made.

**Comment by AquilaSagitta** [comment]
Yes I have a config file in the same directory I'm running err.py if I didn't it throws this:

INFO:root:init plugin manager
ERROR:root:I cannot find the file config.py in the directory /home/aquila/bluefireBOT
(You can change this directory with the -c parameter see --help)
INFO:root:You can use the template /home/aquila/botenv/local/lib/python2.7/site-packages/errbot/config-template.py as a base and copy it to /home/aquila/bluefireBOT/.
You can then customize it.

**Comment by gbin** [comment]
Remove the:
 u'' # 

This basically put an empty string and comment out your parameter.

**Comment by AquilaSagitta** [comment]
I set: 
<code>BOT_LOG_FILE = None</code>
and ran:
<code>err.py -d</code>
INFO:root:init plugin manager
INFO:root:Config check passed...
INFO:root:Checking for '/home/aquila/bluefireBOT'...

That didn't seem to do anything it just stopped after checking that directory. I then ran:
<code>err.py</code>
INFO:root:init plugin manager
INFO:root:Config check passed...
INFO:root:Checking for '/home/aquila/bluefireBOT'...
Traceback (most recent call last):
  File "/home/aquila/botenv/bin/err.py", line 202, in <module>
    main(bot_class, logger)
  File "/home/aquila/botenv/local/lib/python2.7/site-packages/errbot/main.py", line 14, in main
    hdlr = logging.FileHandler(BOT_LOG_FILE)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/var/log/err/err.log'

Could this be a permissions issue? err is trying to do something I don't have permission for which throws python error and it can't make the log file. Is that whats happening? Thanks for the help by the way

**Comment by gbin** [comment]
Check ls -la /var/log to see if the directory is there with the correct rights

**Comment by gbin** [comment]
If you put BOT_LOG_FILE at None and it still tries to write to something, it means the bot did not get your config.py file at all.

try to start it with specifying exactly which config to take:
if your config is let's say /home/aquila/botenv/config.py

Try to start the bot with:
    
    err.py --config /home/aquila/botenv/

**Comment by AquilaSagitta** [comment]
Ok figured out the problem. I had a config file in errbot install directory and even when I explicitly told errbot to use a different config it uses the one in install directory.
