### ISSUE TITLE
Retrieve offline messages

### ISSUE THREAD

**Issue by cyttorak** [gbin/err#336]
Hi

I want to send some commands to my bot although it would be offline, and when my bot go up it retrieves the offline messages and run this commands.

is it possible? how?

**Comment by zoni** [comment]
At the moment, these messages are [logged but discared](https://github.com/gbin/err/blob/master/errbot/backends/base.py#L761-L763), so no, right now this isn't possible.

It would technically be possible to make this option configurable through `settings.py` though, if you feel up to the challenge. :smiling_imp:

**Comment by gbin** [comment]
The rational behind disabling those offline messages is that if Err is going offline then online, the server might notify again a message it treated previously (and potentially a dangerous one).
If we want to do that we probably need to keep track of the last message we actually received and filter the offline messages.

**Comment by gbin** [comment]
A lot of backends have this offline feature now for example:  slack, hipchat, gitter

If somebody has a real need for that and is willing to go through the all those backends to implement the dedup logic of the messages, I am all for it but otherwise I don't think the effort worths it.

**Comment by cyttorak** [comment]
@zoni where is that log with the messages discarded? Maybe I can do a script to manage that messages 

@gbin what about set a flag in botcmd to permit "offline cmds"?. By default a botcmd only would be run by a online message but if a botcmd would have the flag= true it would be also run by offline message.

In that way if someone is developing a botcmd no potentially dangerous he could set this feature for that single botcmd.

**Comment by gbin** [comment]
Maybe we can make a specific callback for them then it is up to the plugins
to sort it out ?

**Comment by cyttorak** [comment]
yes, It would be fine

**Comment by zoni** [comment]
@cyttorak the discarding happens in `base.py` [lines 675 to 677](https://github.com/gbin/err/blob/7f28e427811d84e5223c50e66844f98f1810a980/errbot/backends/base.py#L675-L677).

**Comment by zoni** [comment]
Also, I agree with Guillaume, a callback (`callback_delayed_message` maybe?) so plugins could handle these seems like a good way to go, it would only take a few lines of code to implement.

This would even allow people to write a plugin that re-injects them as regular messages if they wanted this sort of functionality.

**Comment by gbin** [comment]
Maybe we need to give a kind of unique ID along with the message (it would
be backend specific) otherwise plugins have no chance to sort out dupes,
but then we have the problem of live messages vs delayed messages to sort
out...
Still thinking about it so we don't paint ourself it a bad corner.

**Comment by s-nt-s** [comment]
Hi. Is there any news about this issue?. Thanks

**Comment by zoni** [comment]
No progress has been made on this, no.
