### ISSUE TITLE
self.config not a class member

### ISSUE THREAD

**Issue by wildegnux** [gbin/err#341]
using self.config in a @classmethod doesn't work:
@classmethod
def test(self, something):
    print(self.config['TEST'])
    return True

gives me this error when function is used: AttributeError: type object 'Myplugin' has no attribute 'config'
As Guillaume Binet explained on the [g+ page](https://plus.google.com/+DanMalm/posts/VqtuNkXCSX4), this is because self.config is an instance member and not class member. So if that could be fixed that would be great, so we don't have to keep passing the config between functions.

**Comment by gbin** [comment]
Looked into it, the plugin is actually instantiated by yapsy and we populate this object field early on.

The thing is even if we inject that at the class level, all early the life cycle of the class is already done.

If you need it and you are sure that no static method gonna be called before that, I would suggest to override configure in your plugin and do that:

    def configure(self, config):
         self.__class__.config = config

then the static methods will work.
