### ISSUE TITLE
Cannot message MUC rooms, and other MUC problems (XMPP)

### ISSUE THREAD

**Issue by richiebbb** [gbin/err#342]
Hey, love the program.

I'm using python 2 with err on an XMPP server (openfire) and love it, however I'm having some trouble with groupchat related things.

For example:

>self.send(
>    "conference.host.tld/room",
>    "Boo! Bet you weren't expecting me, were you?",
>    message_type="groupchat"
>)

This does not work for me, despite the syntax being correct. (We use a different string instead of "conference" though)
>self.send(
>    "user@host.tld/resource",
>    "Boo! Bet you weren't expecting me, were you?",
>    message_type="chat"
>)
Does work.

Likewise, !room list does not seem to work, it returns
>'XMPPBackend' object has no attribute 'client'

having checked http://errbot.net/_modules/errbot/backends/xmpp/
It appears the class doesn't have client in it, but XMPPconnection does.

Using !room join only seems to add the string that is the room name.

Any help? Sorry if this is a n00b question!

**Comment by zoni** [comment]
Regarding the groupchat messaging, I would expect the server to send an error message, so I would suggest setting the loglevel to `DEBUG` and looking for a log message like the following (tip: grep for `type="error"`):

```
2015-05-13 19:43:35,063 DEBUG RECV: <message from="redacted@conf.hipchat.com" to="redacted@chat.hipchat.com/none||proxy|pubproxy-e6.hipchat.com|5282" type="error">
<body>redacted</body><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You
 must be in this room to send a message.</text></error></message>
```

I will see about catching `type="error"` messages and logging a `logging.error()` message to make this more obvious in the future.

Regarding your other issue, can you tell me what version of Err you are running and how you installed it? (`pip install err`?).

**Comment by richiebbb** [comment]
Hi, I am sorry I took so long to reply. Life has been busy. I really appreciate your help, sorry again about being late.

I discovered
>self.send(
>"**conference.host.tld/room**",
>"Boo! Bet you weren't expecting me, were you?",
>message_type="groupchat"
>)

doesn't work, but

>self.send(
>"**room@conference.host.tld**",
>"Boo! Bet you weren't expecting me, were you?",
>message_type="groupchat"
>)

Does. Note the one that didn't work (for me, at least) is written here:
http://errbot.net/user_guide/plugin_development/messaging/#sending-a-message-to-a-specific-user-or-muc
(I will get Err to send to the original type and look for error logs in the server soon)


I was using Err 2.2.0, now I'm using Err 2.2.1. (Yes, `pip install err`) 

I still have the issue with `!room list` returning `'XMPPBackend' object has no attribute 'client'`

Even after explicitly joining rooms (from the config or from the command) it still shows that error. Also, !room occupants does not work, having supposedly joined the rooms.


Also I just want to say I really love Errbot. Cheers to you all. I was new to python and it really gave me a fun way to experiment with it.

**Comment by gbin** [comment]
so yeah the doc is wrong here:
# Or to send to a MUC
self.send(
    "conference.host.tld/room",
    "Boo! Bet you weren't expecting me, were you?",
    message_type="groupchat"
)

should really be room@...

**Comment by gbin** [comment]
please reopen if it is still an issue.

**Comment by tom-aa** [comment]
@gbin 
I also have the problem of bellow, could you help to check?
python2.7, err 2.2.1
command:  !room list

error:
'XMPPBackend' object has no attribute 'client'
having checked http://errbot.net/_modules/errbot/backends/xmpp/
