### ISSUE TITLE
Detect if the user starts err with the wrong version of interpreter

### ISSUE THREAD

**Issue by gbin** [gbin/err#360]
Starting the py2 err version under py3 or py3 version under py2 causes a very weird error users are unable to understand.

I propose to implement a detection in the code stopping err right at the beginning with a clear message that they are using the generated py2 version under python3 or the most probable vanilla py3 version under py2.

**Comment by zoni** [comment]
This sounds like a good idea. Though I'm not sure how we can reliably detect this.. Perhaps we should save some metadata at `python setup.py install` time, indicating if it was installed for Python 2 or 3.

**Comment by gbin** [comment]
I was thinking about a "smart way" checking for a couple of getattr manually, but maybe just appending something to version.py like `py2_generated = true` if enough

**Comment by gbin** [comment]
Fixed "smartly" with af532b13672f6e262ce191d87b05379bf0c531cf
