### ISSUE TITLE
is_admin and security/access control not working with slack backend

### ISSUE THREAD

**Issue by derekn** [gbin/err#374]
ive tried all combinations of user id, dm id, resource, node, etc and canot get admin access or auth to work with master

**Comment by sijis** [comment]
@zoni I don't thinks its completely broken.
It seems to work if i have the following:
```
BOT_ADMINS = (
    'D01xxxxxxx',
)
````

Unfortunately, I didn't see an easy way to get that UID other than debug. the ```whoami``` command would be nice in this situation.

Sijis

**Comment by zoni** [comment]
Could you try this again using the [issue/374](https://github.com/gbin/err/tree/issue/374) branch? You should then be able to specify the username of a person, instead.

(I'm sorry @sijis, if it gets merged it'll break your use of using the user-ID (the IDs starting with `D`), there was no quick way to support both.)

**Comment by sijis** [comment]
@zoni I'm completely fine with the change. its easier to know a username than an internal UID.

Sijis

**Comment by derekn** [comment]
@zoni this works perfectly so far. thanks!

**Comment by zoni** [comment]
Cool! I'll open a PR so Guillaume can double-check it, and close the issue once it gets merged in.

**Comment by Cobra800089** [comment]
Currently using issue/374 and it still is having an issue finding my user by name in private group:

```
01:13:19 INFO     errbot.backends.base      Processing command 'hello' with parameters '' from D055*****@jordan-beer-bot/jordan/jordan
01:13:19 ERROR    errbot.backends.slack     An exception occurred while trying to send the following message to jordan: Hello, world!
Traceback (most recent call last):
  File "/home/jordan/err/errbot/backends/slack.py", line 296, in send_message
    to_id = self.get_im_channel(self.username_to_userid(to_humanreadable))
  File "/home/jordan/err/errbot/backends/slack.py", line 234, in username_to_userid
    raise UserDoesNotExistError(u"Cannot find user %s" % name)
UserDoesNotExistError: Cannot find user jordan
```

It will print the message to the bot's console, but it won't print it to the channel because it can't find the user.

Any idea if there is a fix for this or if the fix is planned?

**Comment by gbin** [comment]
The recent identifier refactoring should fix this: it is always checked against "frm.person" so the most precise identifier pointing to a person (not a nick, not a name)
For Slack this should be the U023BECGF form.
The new !whoami can give you yours easily.

If it still doesn't work please reopen a bug/PR.

**Comment by zoni** [comment]
Those IDs are really user-unfriendly because normally, you aren't exposed to them. I've opened #399 to change it to usernames again, which is much easier for people to work with.

It allows back-ends to specify what `Identifier` attribute should be used for lookups. The default remains `person` but for Slack, it specifies `nick` instead which is the username.
