### ISSUE TITLE
Semantic versioning? Breaking changes in release notes?

### ISSUE THREAD

**Issue by eykd** [gbin/err#378]
We just today upgraded from Err 2.1 to 2.2.1, since the VersionChecker plugin was badgering us to do so, and our Hipchat integration broke because a new dependency (with new configuration requirements!) was introduced. This was, to say the least, quite unexpected, as there was no mention in the release notes of any breaking changes.

I realize that semantic versioning would be difficult or even impossible w/ 3rd-party integrations like Hipchat a part of the core release, but it would be very helpful to at least have breaking changes documented in the release notes.

**Comment by gbin** [comment]
Ok this is our bad and we apologize.

Indeed we had to change the way hipchat is interacting with the bot but we did not warn for the new identification for the API + the hypchat dependency change.

I'll add a new section to the release note for changes of that nature so we don't forget (stuff that might break you ?).

**Comment by eykd** [comment]
Thank you very much. This will be a big help, I'm sure.
