### ISSUE TITLE
Error when starting up: "Slack API call to channels.join failed: user_is_bot"

### ISSUE THREAD

**Issue by Kaniabi** [gbin/err#385]
I'm getting an error in the Slack API call "channels.join" when starting my err-bot. I'm using a BOT account on Slack to integrate with ErrBot and I believe that this is the problem since "channels.join" cannot be called by a BOT. So I ask:

  How should I integrate with Slack if not using a BOT account?

Thanks in advance!

```
21:34:29 ERROR    errbot.errBot             callback_connect failed for <yapsy_loaded_plugin_ChatRoom_0.ChatRoom object at 0x04174F90>
Traceback (most recent call last):
  File "X:\bos-bot\err-bot\.venv\lib\site-packages\errbot\errBot.py", line 280, in signal_connect_to_all_plugins
    bot.callback_connect()
  File "X:\bos-bot\err-bot\.venv\lib\site-packages\errbot\core_plugins\chatRoom.py", line 37, in callback_connect
    self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
  File "X:\bos-bot\err-bot\.venv\lib\site-packages\errbot\backends\slack.py", line 424, in join
    self._bot.api_call(u'channels.join', data={u'name': self.name})
  File "X:\bos-bot\err-bot\.venv\lib\site-packages\errbot\backends\slack.py", line 122, in api_call
    raise SlackAPIResponseError(u"Slack API call to %s failed: %s" % (method, response[u'error']))
SlackAPIResponseError: Slack API call to channels.join failed: user_is_bot
```

**Comment by sijis** [comment]
There's a [tweet](https://twitter.com/bitlab_co/status/542785009737015296) on this request for bot accounts.

In short you have to invite your bot into the channel.
/invite <botname>

For me, in config.py, I don't have any channels defined as what channels the bot needs to join. Once the bot's invited to a channel, it will stay persistent regardless if err is running or not.

**Comment by Kaniabi** [comment]
Niiice,

In other words, you can't use the CHATROOM_PRESENCE configuration when
working with slack backend. Using this configuration will make the bot try
to join a channel, that is forbidden. Instead you must always invite the
bot to the channel using /invite command. Got it.

Thank you.



Alexandre Motta de Andrade
Gerente de Configuração
www.esss.com.br

**Comment by jasonrhaas** [comment]
Hello, when I try to comment out the `CHATROOM_PRESENCE` in the **config.py** file it gives me an error message saying that it is a required field.

**Comment by zoni** [comment]
@jasonrhaas don't comment it out, but just give it an empty value (`CHATROOM_PRESENCE=()`).

**Comment by jasonrhaas** [comment]
@zoni that works, thanks!
