### ISSUE TITLE
Can I use only TOX backend?

### ISSUE THREAD

**Issue by atommixz** [gbin/err#387]
Cause I can't

**Comment by gbin** [comment]
Hi, can you clarify ?
When you start err with err.py -O, you only use the TOX backend.

[Note that upstream has been broken the last time I tried so you might have to sync at their revision around the same time the Tox backend has been created on our side.]

**Comment by atommixz** [comment]
Ooops... sorry. idk about -O. I just comment/uncomment in config.py. 

Anyway i can't install PyTox on my ArchLinux. I know it's not you trouble.
error: command 'gcc' failed with exit status 1
gcc --version
gcc (GCC) 5.1.0

**Comment by gbin** [comment]
yeah, I have the same issue on my archlinux, it is because they changed their headers on the native code side, somebody ported it in a pull request but it crashed on me.
