### ISSUE TITLE
ImportError: cannot import name resolver

### ISSUE THREAD

**Issue by cyttorak** [gbin/err#393]
Hi
I have this error

~ $err.py

02:00:54 INFO     root                      Config check passed...
02:00:55 ERROR    root                      Could not start the XMPP backend
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/backends/xmpp.py", line 19, in <module>
    from sleekxmpp.xmlstream import resolver, cert
ImportError: cannot import name resolver
02:00:55 CRITICAL root
    If you intend to use the XMPP backend please install the python sleekxmpp package:
    -> On debian-like systems
    sudo apt-get install python-software-properties
    sudo apt-get update
    sudo apt-get install python-sleekxmpp
    -> On Gentoo
    sudo layman -a laurentb
    sudo emerge -av dev-python/sleekxmpp
    -> Generic
    pip install sleekxmpp

but
    sudo apt-get install python-software-properties
    sudo apt-get update
    sudo apt-get install python-sleekxmpp
don't fix the problem.

My linux distribution is Raspbian

**Comment by gbin** [comment]
Can you check if the modules are installed for the correct version of
python (and maybe virtualenv if you use then) ?

**Comment by cyttorak** [comment]
~ $ python --version
Python 2.7.3
~ $ pip freeze --local
3to2==1.1.1
BeautifulSoup==3.2.1
beautifulsoup4==4.4.0
bottle==0.12.8
cffi==1.1.2
chardet==2.3.0
colorlog==2.6.0
config==0.3.9
cryptography==0.9.3
daemonize==2.3.1
dnspython==1.12.0
enum34==1.0.4
err==2.2.1
GnuPGInterface==0.3.2
idna==2.0
ipaddress==1.0.7
jabberbot==0.16
Jinja2==2.7.3
lxml==2.3.2
MarkupSafe==0.23
mercurial==2.2.2
numpy==1.6.2
pafy==0.3.74
periscope==0.2.4
pexpect==3.3
pifacecommon==4.1.2
pifacedigitalio==3.0.5
PIL==1.1.7
pyasn1==0.1.8
pycparser==2.14
pycrypto==2.6
pycurl==7.19.0
pygame===1.9.1release
pygobject==3.8.2
pyOpenSSL==0.15.1
pysqlite==2.6.3
python-apt==0.8.8.2
reportlab==2.5
requests==2.7.0
RPi.GPIO==0.5.11
six==1.9.0
sleekxmpp==1.0b5
unattended-upgrades==0.1
waitress==0.8.9
WebOb==1.4.1
WebTest==2.0.18
whitey==0.4
xlrd==0.9.3
xlutils==1.7.1
xlwt==1.0.0
Yapsy==1.11.223

**Comment by gbin** [comment]
Oh ok, you'll need to avoid the debian repo : sleekxmpp==1.0b5 is really old.

(err-py2)gbin@gbin-macbookpro ~/projects/err> pip install sleekxmpp                                                                                                       
Collecting sleekxmpp
  Downloading sleekxmpp-1.3.1.tar.gz (831kB)

**Comment by gbin** [comment]
Please reopen if it is not that, thx !

**Comment by cyttorak** [comment]
Thanks. Now is working.

~ $ sudo pip install -U sleekxmpp
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90:
InsecurePlatformWarning: A true SSLContext object is not available. This
prevents urllib3 from configuring SSL appropriately and may cause certain
SSL connections to fail. For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
.
  InsecurePlatformWarning
Collecting sleekxmpp
  Downloading sleekxmpp-1.3.1.tar.gz (831kB)
    100% |████████████████████████████████| 831kB 4.4kB/s
Installing collected packages: sleekxmpp
  Found existing installation: sleekxmpp 1.0b5
    DEPRECATION: Uninstalling a distutils installed project (sleekxmpp) has
been deprecated and will be removed in a future version. This is due to the
fact that uninstalling a distutils project will only partially uninstall
the project.
    Uninstalling sleekxmpp-1.0b5:
      Successfully uninstalled sleekxmpp-1.0b5
  Running setup.py install for sleekxmpp
Successfully installed sleekxmpp-1.3.1
