### ISSUE TITLE
IRC colors bleed

### ISSUE THREAD

**Issue by gbin** [gbin/err#409]
It looks like the ANSI code for restoring the colors works on the text backend but not with IRSSI.

**Comment by gbin** [comment]
This is because IRSSI doesn't know fg.default as ANSI, fx.reset kind of works but is it not the same meaning.

**Comment by ailin-nemui** [comment]
did you test this with irssi from git? anyway you should prefer IRC colour codes over ANSI, some clients do not support ANSI at all

**Comment by gbin** [comment]
Just compiled irssi from git, still there:
![image](https://cloud.githubusercontent.com/assets/975564/8860157/e0d98cd8-3136-11e5-8b78-6f2dea4fa932.png)

instead of:
![image](https://cloud.githubusercontent.com/assets/975564/8860167/fdd5bf32-3136-11e5-8a1a-2022cf55ac53.png)

**Comment by gbin** [comment]
Made the translation table for IRC, it works perfectly:

![image](https://cloud.githubusercontent.com/assets/975564/8862010/79077870-3142-11e5-90c5-766df17e2261.png)

Fix in 70818f3fc77a14afb273eac870e45bb5c2a5a4f7

**Comment by ailin-nemui** [comment]
weird, I tried `/exec - python3 -c 'from ansi.color import fg, bg, fx; print(str(fg.red) + "ha" + str(fg.default) + "llo")'` and it shows up properly. anyway :+1: nice IRC renderer
