### ISSUE TITLE
Password protected IRC channels are broken

### ISSUE THREAD

**Issue by dmsimard** [gbin/err#410]
Hey,

Just updated from the latest released version to master branch.
The bot is no longer able to join password protected IRC channels.

Looking at:
https://github.com/gbin/err/blob/master/errbot/config-template.py#L135-L139

What we had configured and worked before was:
CHATROOM_PRESENCE = ['#channelone', ('#channeltwo', 'password')]

The error thrown by the bot is:

    15:57:24 ERROR    errbot.errBot             callback_connect failed for <yapsy_loaded_plugin_ChatRoom_0.ChatRoom object at 0x7fa9ec547490>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 586, in signal_connect_to_all_plugins
        bot.callback_connect()
      File "/usr/local/lib/python2.7/dist-packages/errbot/core_plugins/chatRoom.py", line 31, in callback_connect
        log.debug(u'Try to join room %s' % room)
    TypeError: not all arguments converted during string formatting

Thanks,

**Comment by gbin** [comment]
ho doh, the log message making it crash :)
fdb72dba86633acf22eea0ed2e420b4d4a56a38a <- fixed !

**Comment by dmsimard** [comment]
Confirmed that fixed the issue. Thanks.
