### ISSUE TITLE
Empty line returned after every command

### ISSUE THREAD

**Issue by dmsimard** [gbin/err#412]
Here's what it looks like:

    <dmsimard> !help
    <bot> Available help:
    <bot> !help Backup:  Backup related commands. 
    <bot> !help ChatRoom: This is a basic implementation of a chatroom
    <bot> !help ErrbotLivestatus: An Err Nagios Livestatus Monitoring plugin
    <bot> !help Help: Core plugin of help related functions.
    <bot> !help Help: Core plugin for bot lifecycle and health related commands.
    <bot> !help Plugins: Commands to manage the plugins of the bot by chatting.
    <bot> !help Utils: Core Errbot utils commands.
    <bot> !help Webserver: This is a plugin for enabling webhooks and web interface to err
    <bot> 
    <dmsimard> !help Utils
    <bot> Available commands for Utils:
    <bot> !echo: A simple echo command. Useful for encoding tests etc ...
    <bot> !history: display the command history
    <bot> !log tail: Display a tail of the log of n lines or 40 by default
    <bot> !render test: Tests / showcases the markdown rendering on your current backend
    <bot> !whoami: A simple command echoing the details of your identifier. Useful to debug identity problems.
    <bot> 
    <dmsimard> !echo test
    <bot> test
    <bot> 

This isn't so bad for larger commands (say, !help) but when your command or plugin sends just one line, it quickly clutters the chat.

**Comment by gbin** [comment]
fixed : a47990d1651abc2cbf42a6de66704017c287f389

This was because of the new formatter, it is inserting a blank like at every paragraph so before it was fine:
para1\n
para2\n

but now it insert a formatting reset at the end of the message so:
para1\n
para2\n
\x03

^^ this was an empty line with an invisible RESET (\x03) in it

**Comment by dmsimard** [comment]
Yup, that fixed it. Thanks.

With all those fixes, I think I should be good for the time being. Let you know if there's anything else. Great work :)
