### ISSUE TITLE
Catching exceptions raised from back-ends

### ISSUE THREAD

**Issue by zoni** [gbin/err#418]
I wanted to give Slack users better feedback when trying to have the bot join a room using a bot account, so I came up with [this change](https://gist.github.com/zoni/8be7ae2f704584fe2b9f). (I specifically wanted to avoid silently ignoring this error so that plugin authors can handle it (a plugin might rely on successfully creating/joining a certain room), but provide helpful feedback to the user when doing `.room <join,create,leave,destroy> #someroom` and when having rooms listed in `CHATROOM_PRESENCE`.)

Unfortunately, catching SlackAPIResponseError isn't working. The plugin uses `from errbot.backends.slack import SlackAPIResponseError` and does the following:

``` python
try:
  # Something
except SlackAPIResponseError as e:
  # Something else
```

However, because of how Yapsy loads stuff, the exception that is raised is: `<class 'yapsy_loaded_plugin_Slack_0.SlackAPIResponseError'>`.

So the question is, what would be the best way to go about making this usable?

**Comment by zoni** [comment]
One thing that works is defining the exceptions in another python module. For example, `SlackAPIResponseError` could be defined in `errbot.exceptions`. The slack-backend could import it from there, as could the MUC plugin, and that way it will work without any further modifications.

I actually like the approach of having all exceptions in the same place (`errbot.exceptions`) because it gives a nice overview of all the different exceptions that could be raised.

The one downside to this approach is that for back-ends that aren't a part of Err itself, it would still be very difficult to properly catch them (probably having to get the Yapsy plugin object and referring to it through that) but I think this is a very rare use-case.

**Comment by gbin** [comment]
Sorry but I think this is a wrong approach for 2 reasons:

First it bleeds Slack stuff into the core
Secondly having a package per type is a kind of antipattern. Exceptions are better placed from the semantic package their come from.

 Why no try a generic backend exception embedding the backend one with https://www.python.org/dev/peps/pep-3134/ or something similar like a backend exception with an extra "explanation" string we could present to the user ?

**Comment by zoni** [comment]
> First it bleeds Slack stuff into the core

I don't think it's that bad, but I see your point, and yes it does.

> Secondly having a package per type is a kind of antipattern. Exceptions are better placed from the semantic package they come from.

I disagree, I know of quite a few (high-quality) Python libraries using this pattern. See for example [requests.exceptions](https://github.com/kennethreitz/requests/blob/master/requests/exceptions.py).

Personally I tend to prefer it, it's a lot simpler to find the exception you need to catch than having to import it from `somepackage.subpackage.subsubpackage` but I know of enough people who disagree with that sentiment. :smile:

I will try another implementation using exception chaining (the mentioned PEP 3134) which sounds like a good approach too, though this will cause a bunch of extra exception wrapping to take place, which I was hoping to avoid. :smiling_imp:

**Comment by zoni** [comment]
The use-case that triggered this is now solved (see #421) so I'm closing this issue as it can more or less be worked around by wrapping and raising exceptions from `errbot.backends.base`.

**Comment by lingfish** [comment]
I'm lost as to how to catch SlackAPIResponseError, after all of the above -- can you give a example explaining:

> as it can more or less be worked around by wrapping and raising exceptions from errbot.backends.base.

**Comment by GenPage** [comment]
@lingfish He still catches the SlackAPI specific exception but re-raises a `RoomError` from `errbot.backends.base`

```
except SlackAPIResponseError as e:
            if e.error == "user_is_bot":
                raise RoomError("Unable to join channel. " + USER_IS_BOT_HELPTEXT)
            else:
                raise RoomError(e)
```
