### ISSUE TITLE
Refactoring has broken some stuff

### ISSUE THREAD

**Issue by zoni** [gbin/err#430]
Commit deade3b750b17516f48d103f776040ebfec34ca7 broke Telegram (`TypeError: __init__() got an unexpected keyword argument 'id'`) so we should investigate and ensure none of the other back-ends got broken as well.

(Checkmarked means checked and working OK)

* [x] graphic
* [ ] hipchat
* [x] irc
* [x] slack
* [x] telegram
* [x] test
* [x] text
* [x] xmpp

**Comment by zoni** [comment]
Possibly more brokenness:

```
>>> .help Health
Computer says nooo. See logs for details.:
 name 'ACLViolation' is not defined
```

**Comment by gbin** [comment]
checked graphic and text

**Comment by gbin** [comment]
checked IRC with ngircd
channel, private, formatting
!whoami was broken and fixed

**Comment by gbin** [comment]
ACLViolation, an import was missing:
```
(err)➜  err (master) ag ACLViolation
errbot/backends/base.py
15:class ACLViolation(Exception):

errbot/core_plugins/help.py
73:            except ACLViolation:

errbot/errBot.py
24:from .backends.base import Backend, ACLViolation
279:        except ACLViolation as e:
378:        Raises ACLViolation() if the command may not be executed in the given context
391:            raise ACLViolation("You're not allowed to access this command from this user")
394:            raise ACLViolation("You're not allowed to access this command from this user")
402:                raise ACLViolation("You're not allowed to access this command from a chatroom")
405:                raise ACLViolation("You're not allowed to access this command from this room")
408:                raise ACLViolation("You're not allowed to access this command from this room")
412:                raise ACLViolation("You're not allowed to access this command via private message to me")
418:                raise ACLViolation("You cannot administer the bot from a chatroom, message the bot directly")
420:                raise ACLViolation("This command requires bot-admin privileges")
```

**Comment by gbin** [comment]
hipchat became super ugly (no fixed font with formatting) trying to fix it with /quote in front of every message

**Comment by gbin** [comment]
/quote doesn't work (still not fixed font), /code doesn't work (no mentions).

So for hipchat *nothing formatting* works : html-im doesn't, fixed font doesn't, html in API doesn't.

**Comment by gbin** [comment]
tested XMPP : direct messages OK, group messages OK, DIVERT_TO_PRIVATE OK

**Comment by gbin** [comment]
tested Hipchat, DIVERT_TO_PRIVATE is still impossible but it is a known fact #321 
otherwise it looks ok
