### ISSUE TITLE
HipChat should not use the API to send messages

### ISSUE THREAD

**Issue by zoni** [gbin/err#431]
aef572ab790e0510d247499087039b8f8bf185fd specifically removed using the API for sending general messages because (1) it's trivial to blow through the API limits really fast and (2) things like `@mentions` don't work for `html` messages.

The recent templating refactor has caused it to start using this API again, but I think it's better to send messages over XMPP instead as html-im (or perhaps we can make it a user-configurable option, use API or not).

**Comment by gbin** [comment]
Oh, OK sorry I totally forgot why we were not using the api and switched back to that because html-im doesn't work at all on hipchat.

How low is the api limit vs xmpp limit ?

**Comment by gbin** [comment]
I reverted it.
