### ISSUE TITLE
Slack formatting issue

### ISSUE THREAD

**Issue by LuckyHyena** [gbin/err#440]
test b below formats correctly but test a doesn't

```python
from errbot import BotPlugin, botcmd

class BotTest(BotPlugin):
        @botcmd
        def test_a(self, *args):
                yield '`test code`'

        @botcmd
        def test_b(self, *args):
                yield '<@asdf> `test code`'
```

**Comment by gbin** [comment]
Some analysis...

Apparently it doesn't let "` " go through consistently
![image](https://cloud.githubusercontent.com/assets/975564/9319022/9dd112c2-44fe-11e5-9678-5d19a443b2b3.png)

The md part is apparently got it correctly (you see the code tag in html from the debug console)
![image](https://cloud.githubusercontent.com/assets/975564/9319031/bc081d1c-44fe-11e5-836e-5c0e563ae78e.png)

**Comment by gbin** [comment]
![image](https://cloud.githubusercontent.com/assets/975564/9319296/be98f3d2-4501-11e5-9fca-03ad1bdfa259.png)
