### ISSUE TITLE
 errbot ignore `!` in dynamic re_botcmd.

### ISSUE THREAD

**Issue by fmnisme** [gbin/err#443]
I gen re_botcmd startswith `!` dynamic,for example `^!st2 list rules$ `. If I type `!st2 list rules`,from the debug log I can see it become `st2 list rules` ,so it does not match `^!st2 list rules$`.
It seems that errbot ignore `!` in dynamic re_botcmd.

debug log:
```11:21:23 DEBUG errbot.errBot Matching 'st2 list rules' against '^!st2 list rules$' produced no match 
Command "st2" / "st2 list" not found.```

**Comment by gbin** [comment]
Have your tried with prefixed = False (it should ignore the prefix then rematch it within the regexp) ?
re_botcmd(func, prefixed=False, [...])

Please reopen if this doesn't work.
