### ISSUE TITLE
Implement OTP

### ISSUE THREAD

**Issue by gbin** [gbin/err#451]
Try out: https://pypi.python.org/pypi/pyotp with the Google Authenticator app.

**Comment by gbin** [comment]
Done with https://github.com/gbin/err-otp still some work to do to send secret offline but otherwise it works

**Comment by mrshu** [comment]
@gbin just came here to say this is awesome.

Would you mind giving me a few pointers on how to try it out?

**Comment by gbin** [comment]
as an admin: 
!otp_addcmd [command_name]   # to protect a command by OTP
!otp_secret [somebody]   # to send a qrcode to someone so they can scan it with their freeOTP app
Then when this somebody tries the command, the bot will block it, ask for an OTP and once it is entered by the somebody it should unlock and execute it.

Good luck, you might encounter rough spots, PRs are very welcome !
