### ISSUE TITLE
Pidgin users are seeing double returns from Err, but PSI users dont

### ISSUE THREAD

**Issue by NewAuthority** [gbin/err#459]
Once the bot was up and running I went to get the 'hello world' plugin a go and while typing in commands I keep getting a space with the returns as below:

(9:39:24 PM) Damarcus: !status
(9:39:24 PM) LittleLight:                     Yes I am alive...   With these plugins (L = Loaded, U = Unloaded, B = Blacklisted, C = Needs to be configured):  [L] ACLs  [L] Backup  [L] ChatRoom  [L] Health  [L] HelloWorld  [L] Help  [L] Plugins  [L] Utils  [L] VersionChecker  [C] Webserver  Load , ,  GC 0->51 1->1 2->2                                           Yes I am alive... With these plugins (L = Loaded, U = Unloaded, B = Blacklisted, C = Needs to be configured): [L] ACLs [L] Backup [L] ChatRoom [L] Health [L] HelloWorld [L] Help [L] Plugins [L] Utils [L] VersionChecker [C] Webserver Load , ,  GC 0->51 1->1 2->2        

This is the screenshot from a member in the chat using PSI and everything looks normal:
https://images.discordapp.net/eyJ1cmwiOiJodHRwOi8vaS5pbWd1ci5jb20vcEhneHVzZS5wbmcifQ.hIyv-bg52cs3E39trLOKJhqVdYU.png?format=webp

First I thought it was cause I was an admin, but my buddy using pidgin as well was saying it was happening to him as well, then the psi user chimed in with 'I'm not seeing what you guys are talking about.'

No idea what could be causing this, if this is a pidgin issue or a Err issue, figured I would start here.

**Comment by gowness** [comment]
I'm getting this too, but even worse. Not only am i getting the repeat message , but it doesn't seem to render the html correctly the 2nd go round.

status			2:15:09 PM
errbot		         <message>           Yes I am alive...       Plugins  ┏━━━━━━━━┳━━━━━━━━━━━━━━━━┓ ┃ Status ┃ Name           ┃ ┡━━━━━━━━╇━━━━━━━━━━━━━━━━┩ │ A      │ Backup         │ ├────────┼────────────────┤ │ A      │ ChatRoom       │ ├────────┼────────────────┤ │ A      │ GitBot         │ ├────────┼────────────────┤ │ A      │ Health         │ ├────────┼────────────────┤ │ A      │ Help           │ ├────────┼────────────────┤ │ A      │ Jira           │ ├────────┼────────────────┤ │ A      │ Plugins        │ ├────────┼────────────────┤ │ A      │ PollBot        │ ├────────┼────────────────┤ │ A      │ Utils          │ ├────────┼────────────────┤ │ A      │ VersionChecker │ ├────────┼────────────────┤ │ A      │ Webserver      │ └────────┴────────────────┘  A = Activated, D = Deactivated, B = Blacklisted, C = Needs to be configured  Load 0.0, 0.05, 0.02 GC 0->32 1->11 2->4                                           <h2>Yes I am alive...</h2> <h3>Plugins</h3> <table> <thead> <tr> <th>Status</th> <th>Name</th> </tr> </thead> <tbody> <tr> <td>A</td> <td>Backup</td> </tr> <tr> <td>A</td> <td>ChatRoom</td> </tr> <tr> <td>A</td> <td>GitBot</td> </tr> <tr> <td>A</td> <td>Health</td> </tr> <tr> <td>A</td> <td>Help</td> </tr> <tr> <td>A</td> <td>Jira</td> </tr> <tr> <td>A</td> <td>Plugins</td> </tr> <tr> <td>A</td> <td>PollBot</td> </tr> <tr> <td>A</td> <td>Utils</td> </tr> <tr> <td>A</td> <td>VersionChecker</td> </tr> <tr> <td>A</td> <td>Webserver</td> </tr> </tbody> </table> A = Activated, D = Deactivated, B = Blacklisted, C = Needs to be configured Load 0.0, 0.05, 0.02 GC 0->32 1->11 2->4                            			2:15:09 PM

**Comment by gbin** [comment]
Ho so really, the client renders the text version AND the HTML version ! 
(@NewAuthority you did try to do this with no effect, but this looks really like this is the issue)

https://github.com/gbin/err/blob/master/errbot/backends/xmpp.py#L543

remove either the mhtml or put the mbody to '' 

Please report if it improves it. If it is improving, we will need to think about a correct way to fix this.

**Comment by gowness** [comment]
setting mbody to empty didn't change anything, removing mhtml did correct this issue though, 

Thanks!

**Comment by zoni** [comment]
I suspect the issue occurs because Err is sending an incorrectly formatted message.

Some debugging turned out that Err generates a stanza such as the following:

```html
<message type="chat" xml:lang="en" to="132302_958277@chat.hipchat.com">
  <body>Load 0.26, 0.52, 0.63</body>
  <html xmlns="http://jabber.org/protocol/xhtml-im">
    <body xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
      <html xmlns="http://jabber.org/protocol/xhtml-im">
        <body>
          <div style="font-family: monospace">
            <p style="margin-top: 10px; margin-bottom: 0; margin-left:15px;">Load 0.26, 0.52, 0.63</p>
          </div>
        </body>
      </html>
    </body>
  </html>
</message>
```

This has a `<html><body>` pair attached under another `<html><body>` element pair, while [the spec](https://xmpp.org/extensions/xep-0071.html#concepts) uses just a single pair:

``` html
<message>
  <body>hi!</body>
  <html xmlns='http://jabber.org/protocol/xhtml-im'>
    <body xmlns='http://www.w3.org/1999/xhtml'>
      <p style='font-weight:bold'>hi!</p>
    </body>
  </html>
</message>
```

Adjusting the [code in send_message()](https://github.com/gbin/err/blob/master/errbot/backends/xmpp.py#L533-L542) can probably resolve this issue.

**Comment by gbin** [comment]
This bug is obsolete : https://github.com/gbin/err/blob/master/errbot/backends/xmpp.py#L534 and #467 

At the moment xhtml-im is disabled with no clear way on how to reenable it.
