### ISSUE TITLE
Fancy markdown rendering is undesirable on IRC

### ISSUE THREAD

**Issue by zoni** [gbin/err#470]
Because of IRC's every-line-is-a-message operation (unlike all other backends where a message can consist of many lines), users are expressing a dislike of all the "overhead" that formatted markdown is adding to certain commands, such as `!status`.

Perhaps we can disable or tune this on IRC while leaving the other backends unchanged, or perhaps we need to simplify the output of `!status` somewhat.

References:
https://gitter.im/gbin/err?at=55f6e9b2fe4ca46810e191a4
https://plus.google.com/+Dani%C3%ABlCFPFranke/posts/bWryx85y9K3

**Comment by gbin** [comment]
I'd like to have more feedback on this.
I suspect the culprit is formatted table, am I right 
If we remove the drawing boxes is it good enough ? Ansi colors too ?
We can make IRC specific options for the formatter.

**Comment by mrshu** [comment]
@gbin It's mostly the drawing boxes, yes. I believe many people would agree that colors just do not belong to IRC. Most modern IRC clients, however, can render ansi colors without big problems.

Having IRC specific options looks like the best way of dealing with this.

**Comment by gbin** [comment]
done with #480
