### ISSUE TITLE
build_identifier("#channel") should be possible on Slack.

### ISSUE THREAD

**Issue by ph7vc** [gbin/err#477]
First, gotta say; very good job on the bot!

I'm making a plugin that requires me to send a message to a channel, but not to a specific user, on Slack ( would like it to work everywhere tho). I dug through the source and found 2 potential methods: `send` and `bare_send`

`send` will not let me simply send a message without specifying a user, and `bare_send` doesnt seem to work at all on Slack.

The only solution I can think to do is to get a random person from the channel and send it to them as a groupchat.

Not sure if what I want is built in to the bot or not. Any help would be greatly appreciated!

Thanks!

**Comment by gbin** [comment]
indeed, this is a bug:
Basically here the user should be optional : https://github.com/gbin/err/blob/19c055cfe1e9bfdcf513007d795030d60e5c807b/errbot/backends/slack.py#L398
(it is unused afterwards when we send to the channel anyway)

We should allow the creation of identifier in the form of `#channel` here: https://github.com/gbin/err/blob/master/errbot/backends/slack.py#L423

**Comment by zoni** [comment]
@ph7vc I've cobbled together a number of changes in #534 which should make this possible (along with some extra cases).
