### ISSUE TITLE
Remove need for foo.plug

### ISSUE THREAD

**Issue by jamesob** [gbin/err#485]
First off: thanks for the awesome framework! This is really refreshing coming from Hubot-land.

The `.plug` files feel really clunky, and I think there has to be a way to embed the current `.plug` data into the plugin classes themselves.

What's the particular technical limitation that motivated use of `.plug` files in the first place? Would you be open to exploring ways around this?

**Comment by mrshu** [comment]
@jamesob while I am in no position to comment on this I believe they are required for the plugin system to work as it is a crucial part of [`yapsy`](https://yapsy.readthedocs.org/en/latest/PluginManager.html#plugin-info-file-format). Changing that would basically mean either extensively changing the way `err`'s plugin system works currently or abandoning it completely. 

That being said, I personally think that having metadata on plugins in a format that does not require a full Python parser is not a bad thing, even though it might feel a bit clunky.

**Comment by jamesob** [comment]
ah, I see. Thanks for the information, @mrshu!
