### ISSUE TITLE
[API Question] - List MUC occupants?

### ISSUE THREAD

**Issue by dyerrington** [gbin/err#489]
Sorry for polluting the "issues" with a question, but I've been looking around at the code and find references to "occupants" and "get_room" but when I try to reference some of these methods, I'm getting errors.  I know I'm not using these in the right way.

I read this:

> In order to implement the various MUC related APIs you'll find from Backend, you'll need to implement a Room class. To help guide you, you can inherit from MUCRoom and fill up the blanks from the NotImplementedError.

Is there a practical way to get the room occupants from within a botplugin instance method?

**Comment by gbin** [comment]
From your plugin:
https://github.com/gbin/err/blob/master/errbot/botplugin.py#L377
You get this object:
https://github.com/gbin/err/blob/master/errbot/backends/base.py#L477
so something like self.query_room("blah").occupants 
should work.

**Comment by dyerrington** [comment]
I tried this exactly.  `self.query_room(self.channel).occupants` and I thought I needed extend it differently but perhaps there's something lower level at play?  At least, I should be able to look at this part of the code and look further.

Here is the error I get:

```
Traceback (most recent call last):
  File "/Users/davidyerrington/virtualenvs/data/lib/python2.7/site-packages/errbot/errBot.py", line 359, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/Users/davidyerrington/virtualenvs/data/livecoding.tv/chatbot/wilford/plugins/err-mucutils/mucutils.py", line 180, in crash
    print self.query_room(self.channel).occupants
  File "/Users/davidyerrington/virtualenvs/data/lib/python2.7/site-packages/errbot/backends/xmpp.py", line 248, in occupants
    occupants.append(XMPPMUCOccupant(occupant.node, occupant.domain, occupant.resource))
AttributeError: 'dict' object has no attribute 'node'
```

**Comment by benhoff** [comment]
What version of the are you running?
https://github.com/gbin/err/blob/master/errbot/backends/xmpp.py#L252
^ This appears to be where your code is breaking down and it's completely different in the repo than what you posted. 

Just tryin' to help :)

**Comment by dyerrington** [comment]
Upgrading my version of errbot totally fixed this issue!  Thanks @benhoff !

**Comment by benhoff** [comment]
Glad to help!
