### ISSUE TITLE
Community link in README broken

### ISSUE THREAD

**Issue by t2d** [gbin/err#490]
https://plus.google.com/communities/117050256560830486288 returns 403

**Comment by sijis** [comment]
Really, i just tried and it works. Could you retry?

**Comment by gbin** [comment]
maybe it is broken when you are not google logged in ?

**Comment by t2d** [comment]
This is probably the reason, since it says status code 403.

> 403. That’s an error.
> 
> Sie haben keinen Zugriff auf diese Seite. That’s all we know.

It would be nice, if the community would be at least readable anyway or
redirect to login. (Even if I have no google account.)

**Comment by sijis** [comment]
I'm not logged in and I'm not seeing a 403. I'm able to browse the contents of the community but unable to post. Its possible @gbin changed some community settings between your last post and me checking just now.
![screenshot from 2015-10-05 09-06-06](https://cloud.githubusercontent.com/assets/618177/10282425/75722b50-6b40-11e5-916a-b09e64c1f599.png)

**Comment by t2d** [comment]
yes, settings have been changed. thank you
