### ISSUE TITLE
Error in wiki

### ISSUE THREAD

**Issue by fernand0** [gbin/err#513]
In  https://github.com/gbin/err/wiki Authentication seems to be posting to a wrong place.

**Comment by gbin** [comment]
You mean the link of the plugin named `Authentication` ?

**Comment by gbin** [comment]
Ho I got it, those are not errbot plugins but using yapsy for a minecraft thing ;) JSON-based inter-server communications system for Minecraft servers

**Comment by gbin** [comment]
Fixed thx for the feedback !
