### ISSUE TITLE
Document self.mode and self._bot

### ISSUE THREAD

**Issue by gbin** [gbin/err#517]
Sometimes there are backend features that are just impossible to implement through a standardized API.

We have bypass mechanism for that with self._bot.

It should be clear in the documentation that this is very fragile and if something can be done through the standard API it should be done that way and that for a public plugin, it has to be protected by an if self.mode == '...'.

**Comment by zoni** [comment]
This is now documented at http://errbot.net/user_guide/plugin_development/backend_specifics.html.

Additional suggestions always welcome.
