### ISSUE TITLE
The !help <command> command is broken in 3.1.0

### ISSUE THREAD

**Issue by Kromey** [gbin/err#518]
Running Pythong 3.4.3, upon upgrading from Err 3.0.5 to 3.1.0: when running e.g. `!help Utils`, the following Python error is thrown (stack trace omitted):
UnboundLocalError: local variable 'mess' referenced before assignment

The stack trace references line [70 of help.py](https://github.com/gbin/err/blob/3.1/errbot/core_plugins/help.py#L70), and some quick perusing suggests that it was broken in 5081b8d.

This issue does not exist in the master branch, however, where 54692e4 has already fixed it. Alternatively, simply rewriting the local `mess` variable to `msg`, without changing the signature of the `may_access_command` method, also remedies the issue, although the former approach seems a better resolution in any case.

An argument-less `!help` does not provoke the error.

**Comment by gbin** [comment]
Awesome bug report, thx a lot ! fixed by cherry-picking the fixing commit you pointed out.
