### ISSUE TITLE
md_escape only escapes [ '{', '}' ]

### ISSUE THREAD

**Issue by richiebbb** [gbin/err#519]
Hi, love the program, recently upgraded to 3 and needed to escape some things to avoid it being seen as markdown.

In `/errbot/rendering/__init__.py`, we have:
```
def md_escape(txt):
    """ Call this if you want to be sure your text won't be interpreted as markdown
    :param txt: bare text to escape.
    """
    txt = txt.replace('{', '\{')
    txt = txt.replace('}', '\}')
    return txt
```

This only replaces `{` and `}`. I replaced my local copy with:
```
    """ Call this if you want to be sure your text won't be interpreted as markdown
    :param txt: bare text to escape.
    """
    for char in Markdown.ESCAPED_CHARS:
        txt = txt.replace( char, '\\' + char)
    return txt
```
which works.

Not really sure if this is an issue or if I'm making some sort of mistake in my usage, so feel free to close this if it is irrelevant.

**Comment by zoni** [comment]
Since @gbin wrote all the markdown stuff I'll wait for him to confirm, but I think your version is the proper way to do it indeed. Would you be willing to open a pull request with these changes applied?

**Comment by gbin** [comment]
Indeed @richiebbb it is quite incomplete, I am fixing it.
