### ISSUE TITLE
Problem with from .ansi import....

### ISSUE THREAD

**Issue by fernand0** [gbin/err#524]
Ubuntu 14.04.3 LTS 
Python 2.7
errbot 3.1.1

I've updated and when launching the bot there is an error (1)

which seems to be related with err/errbot/rendering/ansi.py  masking the system's ansi module.

I've changed:
ansi.py  to l_ansi.py (local)
and the lines in __init__.py 
    from .ansi import AnsiExtension
to:
    from l_ansi import AnsiExtension

I do not know enough python and I have not found references to this . notation (there are some references to imports with dots:  from . import whatever ), so I'm not sure if this is a problem of the bot, or just a misconfiguration in my system or I'm missing something.

Thanks!

(1) 

> Traceback (most recent call last):
  File "/usr/local/bin/err.py", line 9, in <module>
    load_entry_point('err==3.1.1', 'console_scripts', 'err.py')()
  File "/usr/local/lib/python2.7/dist-packages/errbot/err.py", line 260, in main
    main(backend, logger, config, restore)
  File "/usr/local/lib/python2.7/dist-packages/errbot/main.py", line 89, in main
    bot.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/errbot/backends/xmpp.py", line 540, in serve_forever
    self.conn.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/errbot/backends/xmpp.py", line 346, in serve_forever
    self.client.process(block=True)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/basexmpp.py", line 246, in process
    return XMLStream.process(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 1454, in process
    self._process()
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 1513, in _process
    self.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 690, in disconnect
    args=(reconnect, wait, send_close))
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/thirdparty/statemachine.py", line 70, in transition
    func=func, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/thirdparty/statemachine.py", line 111, in transition_any
    return_val = func(*args,**kwargs) if func is not None else True
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 721, in _disconnect
    self.stream_end_event.wait(4)
  File "/usr/lib/python2.7/threading.py", line 620, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 358, in wait
    _sleep(delay)

**Comment by gbin** [comment]
how is this different from the travis-ci setup under py2.7 ?

**Comment by fernand0** [comment]
I'm very sorry but I'm not familiar with travis-ci. Nevertheless, I can see at.
https://travis-ci.org/gbin/err/jobs/88390605
that it seems to be using python 2.7.9 and my tested versions are: 2.7.6 on Ubuntu 14.04.3 LTS and Python 2.7.3  on Raspbian GNU/Linux 7. 
I cannot say if this makes the difference or not. I'll try to check further on the weekend.

**Comment by fernand0** [comment]
Update. Testing on Ubuntu 15.10, Python 2.7.10 so I'm starting to believe that the problem is with minor versiones of Python 2.7. Unfortunately I cannot test in 2.7.7 and 2.7.8 and, of course, I cannot be sure if this is the problem or not.

**Comment by fernand0** [comment]
Update. Testing on Ubuntu 15.10, which has python 2.7.10 everything seems to be working ok. I'm tempted to believe that there is some problem with 2.7.6 and maybe some versions of python previous to 2.7.9. Unfortunately I cannot test with 2.7.7 and 2.7.8.
Of course I cannot say if this is the actual problem but if it is, python version in Ubuntu LTS is not adequate for errbot.

**Comment by gbin** [comment]
you mean the tests pass on 2.7.10 ?

**Comment by gbin** [comment]
maybe you can use https://github.com/yyuu/pyenv ?

**Comment by fernand0** [comment]
Well. I'm trying to install 2.7.9 in Ubuntu LTS  to check whether in that machine it solves the problem or not (changing the name to l_ansi.py also solved the problem). If it works, I'll assume that the problem is with some previous version of 2.7 and we'll have learned that one needs to be careful with minor versions.

**Comment by zoni** [comment]
I cannot reproduce this on Ubuntu 14.04, not even when installing to the system Python.

That said though, it's a very bad idea to `pip install` anything into the system interpreter as this may replace python packages provided by the distribution itself.

I would recommend you install in a virtualenv and see if your problems persist then. If you don't know how to use virtualenv, it works like this:

```
# In case you don't have virtualenv installed:
apt-get install -y python-virtualenv

# Create the actual virtualenv in ~/errbot (adjust this as desired) using system python2
# as interpreter
virtualenv -p /usr/bin/python2 ~/errbot

# Install errbot
~/errbot/bin/pip install err

# Run it
~/errbot/bin/errbot

# Alternatively, you can make the virtualenv active in this shell session so that you
# don't have to provide the full path to ~/errbot/bin/python, ~/errbot/bin/pip or
# ~/errbot/bin/errbot by using:
source ~/errbot/bin/activate
```

**Comment by fernand0** [comment]
Hello again. I've installed err in my LTS machine with pyenv (as suggested), Python 2.7.10, and it has no errors. Maybe the problem is what you suggest in your last message "That said though, it's a very bad idea to pip install anything into the system interpreter as this may replace python packages provided by the distribution itself."
pip seems to be installing packages in /usr/local so no replacing should occur (maybe I'm wrong) but maybe there is some bad interaction or something similar.
Until recently I've been using python only for small programs and scripts.

At the end, my conclusion is that I need to learn to manage these tools (pyenv, virtualenv) that seem to be able to solve the problem of having several versions without making the whole system unmanageable.

I think that the issue can be closed since you couldn't reproduce it and I'm not sure about the 'sanity' of my local installation of python packages.

Sorry for the noise and keep up the good work!

**Comment by gbin** [comment]
@fernand0 no problem !
