### ISSUE TITLE
test_storage() in tests/utils_tests.py depends on having a (configured) config.py file

### ISSUE THREAD

**Issue by anitawoodruff** [gbin/err#541]
It tries to do "from config import BOT_DATA_DIR" near line 53 which obviously will fail if you haven't copied a config file and given it a valid BOT_DATA_DIR.

Most people will have one for running the bot so won't notice this, but as @gbin said, "Tests should be hermetic anyway and not depend on config".

**Comment by gbin** [comment]
Fixed by 1c7429ae17e166e13a6e67edb036daf14fb984bd
