### ISSUE TITLE
feature request: auto reconnect on kick for irc backend

### ISSUE THREAD

**Issue by nvdk** [gbin/err#72]
Err sometimes gets kicked for flooding on our channel, it would be nice if there was an auto reconnect option

**Comment by dmsimard** [comment]
+1

**Comment by plarivee** [comment]
+1

**Comment by gbin** [comment]
This is by default 5 seconds but can be set from the config file.

Thanks for your patience on this one !

**Comment by dmsimard** [comment]
Hey gbin, there is in an important distinction between re-joining after being kicked from a channel and being disconnected (e.g, connection reset by peer, flooding). This commit looks like it addresses being kicked and not the latter. The latter would be particularly interesting :)

**Comment by gbin** [comment]
@dmsimard indeed, 2 separate problems, we have an internal mechanism for all the backends for that, it looks like the IRC one doesn't use it, I am looking into it.

**Comment by gbin** [comment]
@dmsimard, here we go, done.

The first issue was a long 60s wait to reconnect after disconnection. (now it is a setting + defaults at 5s)

Then we were not calling the disconnect_callback so Err did not know we lost our presence on the rooms.
