### ISSUE TITLE
get_jid_from_message & DIVERT_TO_PRIVATE message from MUC (groupchat)

### ISSUE THREAD

**Issue by apophys** [gbin/err#82]
When I try to execute a command from MUC while the command is in the DIVERT_TO_PRIVATE tuple, *get_jid_from_message* resolves only resource (in this context the nickname) and the response is addressed to that resource only resulting in invalid stanza.

Correct addressing, according to XEP-0045 would be to reply to 'from' attribute of groupchat message, if the idea is to reply with private message in the chatroom.

> DEBUG:deduced the jid from the chatroom to apophys
> DEBUG:Message filtered thru JabberClient : \<message xmlns="jabber:client" to="apophys" type="chat" from="apo-bot@dev-it.org">

**Comment by gbin** [comment]
This area completely changed because we dropped the xmpp conventions, please retest and open a different bug if it still fails.

**Comment by pirxthepilot** [comment]
I'm trying to get my plugin to get this particular stanza from `callback_presence` but the Presence object does not seem to have it?

```
<x xmlns="http://jabber.org/protocol/muc#user">
    <item affiliation="owner" jid="user@server.tld/resource" role="moderator"/>
</x>
```

What's the best way to get this information? (the data inside <item> in particular)
