### ISSUE TITLE
get_jid_from_message not returning JID in groupchat

### ISSUE THREAD

**Issue by joshuatobin** [gbin/err#90]
Hi I'm wondering if you've heard any issues of get_jid_from_message not returning properly when in a chat room. I've become (probably too) dependent on this function for a bunch of my err- plugins. Right now the only way I can successfully get the JID of the user sending a message is by PM'ing errbot. But if I try to retrieve the JID of the user sending a message in a chat room, it always returns the JID of the room, rather than the user.

**Comment by gbin** [comment]
this is really old and this area of the bot completely change, please reopen another bug if this is still true with the new implementation
